package com.laundromat.delivery.model.order;

public enum OrderStatus {

    REQUESTED, ACCEPTED, PICKUP_REQUESTED, PICKUP_ACCEPTED, PICK_UP,
    COLLECTED, IN_SERVICE, WASHED, DELIVERY_REQUESTED,
    DELIVERY_ACCEPTED, DELIVERING, COMPLETED, CANCELLED, DECLINED
}
